### ISSUE TITLE
combing data with rbind

### ISSUE THREAD

**Issue by benwhalley** [ajwills72/rminr#14]
Andy - am posting this here so it doesn't get lost - it's not urgent though.

In this file you show `rbind`: https://ajwills72.github.io/rminr/risk-rat.html

In the context of later showing them how to left_join (a common requirement, e.g. to bind demographic to experimental data) it might be better to show them bind_rows from tidyverse:

This causes an error:
```
rbind(
  tibble(a=1),
  tibble(b=2)
)
```

Whereas this creates NA for B in row 1, and for A in row 2:

```
bind_rows(
  tibble(a=1),
  tibble(b=2)
)
```

We can then later show:

```
bind_cols(
  tibble(a=1),
  tibble(b=2)
)
```

And more usefully:

```
left_join(
  tibble(id=c(1,1,1,2,2,2,3,3,3), RT=c(222,223,255,111,132,121,555,556,555)),
  tibble(id=c(1,2), age=c(20,40))
)
```

**Comment by ajwills72** [comment]
Ah, OK. Yes, fine with using bind_rows, will change in time for 2019/20 use of materials. We might want to talk more abut left_join versus merge, but let's make that a separate issue log?

**Comment by ajwills72** [comment]
Modified as requested, as part of changes for 2019-20 version.
