### ISSUE TITLE
APA tables in "Better tables" worksheet

### ISSUE THREAD

**Issue by earcanal** [ajwills72/rminr#25]
As this is the "_Better_ tables" worksheet, we should make APA tables the path of least resistance. I don't think this is possible with HTML, as the styling needs to be done with CSS; only the HTML is included when copy-pasting from RStudio into a word processor table.

So I'm proposing that we recommend generating tables as images using `kableExtra` in `latex` mode.

Example code:

```
descriptives_table %>%
  kable("latex", col.names = c('Task', 'Male', 'Female'), booktabs = T, align = 'r') %>%
  kable_styling(latex_options = c("scale_down")) %>%
  as_image('table1.pdf')
```

Output:

![image](https://user-images.githubusercontent.com/1086888/87283138-e6b26b80-c4ec-11ea-8c6e-e02e91bec8a7.png)

I would also include an example of generating an HTML table for people who want to copy-paste and do the styling using their word processor's table feature.

This approach would require installing some additional packages ([details here](http://haozhu233.github.io/kableExtra/save_kable_and_as_image.html)):
```
install.packages("magick") # ... which requires ImageMagick and possibly Ghostscript (dev) libraries
install.packages("webshot")
webshot::install_phantomjs()
```

**Comment by ajwills72** [comment]
My suggestion -- not sure I see the point of saving out as PDF, as Word does not import PDF, I think? For wordprocessor users, then, a better solution would be to output as image, covered at 

http://haozhu233.github.io/kableExtra/save_kable_and_as_image.html

This also has the advantage that it has fewer odd dependencies. The link above strongly hints that getting this to work on a Windows system is a real pain (depends on things like ghostscript, which isn't well supported in Windows). Not an issue for our students, but an issue for anyone trying to use this on their own, Windows machine.

**Comment by earcanal** [comment]
That link is the same as the one I included. Did you mean to link to something else?

All image functions on [http://haozhu233.github.io/kableExtra/save_kable_and_as_image.html](http://haozhu233.github.io/kableExtra/save_kable_and_as_image.html) require those odd libs.

**Comment by ajwills72** [comment]
- Link as intended. 
- OK, did not realise those weird things were also needed for e.g. PNG also.
- Did you try package 'apaTables' ? This seems to do APA tables and put them in DOC format.

**Comment by earcanal** [comment]
1. [apaTables::apa.cor.table](https://dstanley4.github.io/apaTables/articles/apaTables.html#correlation-table) looks like a quick solution to APA correlation matrices which are very similar to those in the dissertations.
1. However, because it tends to use a 1:1 (test:table) pattern, it's not so good for "custom" tables. For example, I can't see a way to layout the descriptives for multiple tests in a single table (see example table above, which was the layout as reported in the dissertation). There are a number of these custom tables in the dissertations I looked at.

We could:

1. Generate these "custom" tables as HTML, and indicate that they'll need to use their word processor to make them conform to APA style.
1. Suggest they present them as separate tables, e.g. using `apa.1way.table`, which generates this:
 
![apaTable_apa 1way table](https://user-images.githubusercontent.com/1086888/87315278-36f4f200-c51c-11ea-874f-95f25919d00e.png)

**Comment by ajwills72** [comment]
Ah, yes, OK, I see. 

As you say, multiple tables instead of one is always an option, but probably not always that desirable in all cases. 

So, yes, I suggest also having a 'custom' tables section. And, yes, I guess that will have to say, some hand-formatting in your wordprocessor may be needed. 

It might also say that an alternative is to generate your whole report with R using Rmarkdown, and not use a wordprocessor at all. And then link to some external resource on how to do that? 

In an ideal world, we'd have our own resources on reproducible manuscripts using Rmarkdown, but there's no slot for this in the UG curriculum as it stands.
