### ISSUE TITLE
Required packages not installed on https://rstudio.plymouth.ac.uk/

### ISSUE THREAD

**Issue by earcanal** [ajwills72/rminr#27]
* [see](https://github.com/ajwills72/rminr/blob/ae027b13f525069f7e1448ef84c6866fa13f3ba3/src/cs-picture-naming.Rmd#L461)

**Comment by benwhalley** [comment]
Have added `see` to site packages (package version from 29th June 2020 on line with all the others) so perhaps try and build everything on the server now as a final test?

**Comment by ajwills72** [comment]
Thanks, Ben. Yup, good idea - will leave this to Paul (Paul, obv. don't forget to delete see from your home folder, otherwise it'll just use that).

**Comment by earcanal** [comment]
Works for me.
