### ISSUE TITLE
Better tables - dead link and problem exporting to word

### ISSUE THREAD

**Issue by benwhalley** [ajwills72/rminr#36]
Hi - had question from student who was using the better tables doc.

Where is suggests using kable to make tables to copy and paste into word, it says:

>Try copying the table into your word processor now. In the Viewer pane, select all of the rows and columns in the table, then right-click and select Copy. Open your word processor and select Paste.

Unfortunately this doesn't work on a Mac in Safari. It does work in Chrome, but  it might be worth adding a note that ymmv

You can also pipe the kable to `save_kable(file = 'mytable.html')` which will save an html file in the current directory. If you download that and open it in MS Word that works fine.

Also on that page they spotted a dead link to: https://benwhalley.github.io/rmip/worksheet-recoding.html

This should now be: https://benwhalley.github.io/rmip/data.html#using-recode  But it would probably also be worth extracting that part and repeating it in the stage 4 worksheet here https://ajwills72.github.io/rminr/preproc-scales.html  That page currently has the same dead link to the old recoding page.

**Comment by earcanal** [comment]
Hope it's OK to resolve this for now with a sentence about Mac cut and paste and fixed URL. I removed the link to the explanation of `!!!` as I think Ben removed that. This can be re-opened if duplicating the `recode` technique into "preprocessing scales" is the preferred fix.
