### ISSUE TITLE
Dead "cleaning up questionnaire data" URL 

### ISSUE THREAD

**Issue by paulsharpeY** [ajwills72/rminr#39]
The URL under "cleaning up questionnaire data" has moved. I think the URL is now https://benwhalley.github.io/rmip/data.html#using-recode

**Comment by ajwills72** [comment]
I don't know which section you are referring to, Paul - name of the Rmd document at least, please :-) 

However, I think you have editing access to the repo, so perhaps the most efficient route from here would be for you to directly fix the link in the repo?
