### ISSUE TITLE
Change to preprocessing subscales page?

### ISSUE THREAD

**Issue by ajwills72** [ajwills72/rminr#47]
Jon May writes:

Can I suggest a change to the https://www.andywills.info/rminr/preproc-scales.html#subscales page?

I find having to count the column numbers for rowMeans and rowSums to be very error prone, and ask my students to use pivot_longer, group_by, and summarise instead, followed up with left_join() if needed. I don’t know if by this point students have encountered pivot_longer()  or left_join(), but I’m sure they’ve used group_by() and summarise().

The code is longer, but much easier to read and debug. 

It also (later) allows discontinuous selections using select(starts_with(…))

Compare the two following sections :

Current section from page:
Calculating subscale scores

Our next step is to calculate the scores for the constructs measured by our scale. Many scales consist of groups of questions which measure multiple, distinct constructs. The DASS-21 is an example of a scale with subscale scores for depression, anxiety and stress. These are calculated by adding together responses for specific items, which we can do using the rowSums() function.

Enter these commands into your script, and run them:

dass21 <- dass21 %>%
  mutate(depression = rowSums(dass21[4 + c(3,5,10,13,16,17,21)]))
dass21_total <- dass21 %>% select(partID, Age, Gender, depression)

Explanation of command:

    We use mutate() to create a depression column which is the sum of items 3, 5, 10, 13, 16, 17 and 21. Item 1 of the DASS-21 data is in column 5 of dass21, so we add 4 to each item number to select the correct columns to add together. The command dass21[4 + c(3,5,10,13,16,17,21)] is an example of “vectorised addition”. It adds 4 to each of the columns defined in the vector to the right of the +. For each row, the values in the resulting columns are added together using rowSums(). We assign the result back to dass21, thereby creating a depression column for each row.

How I would change it: (sorry about the formatting, not quite as intended)
Calculating subscale scores

Our next step is to calculate the scores for the constructs measured by our scale. Many scales consist of groups of questions which measure multiple, distinct constructs. The DASS-21 is an example of a scale with subscale scores for depression, anxiety and stress. These are calculated by adding together responses for specific items, which we can do using the rowSums() function.

Enter these commands into your script, and run them:

dass21_dep <- dass21 %>% select(partID, Age, Gender, DASS3, DASS5, DASS10, DASS13, DASS16, DASS17, DASS21)%>%

  pivot_longer(DASS3:DASS21) %>%

  group_by(partID, Age, Gender) %>%

  summarise(depression = sum(value))  

Explanation of command:

    We create a new data frame dass21_dep by selecting the variables we want to use to identify each case partID, Age, Gender, and the ones we want to find the total from DASS3, etc. Line 2 converts the data from wide format (with each variable in a column) to long format (each value in a row) by putting each DASS score into a single column called value, with the variable name in a column called name . Lines 3 and 4 adds a depression column  for each combination of partID, Age, Gender  by  adding together all of the values for that combination (i.e., the scores on each DASS question). The new frame ends up with just four columns, partID, Age, Gender, depression 

(A separate point is that it is usually better to find the mean of a subscale rather than the total (using na.rm=TRUE) as the result is on the same scale as the original question).

They would then need to know how to combine dass21_dep with dass21_anx and dass21_stress using dass21_totals <- left_join(dass21_dep, dass21_anx) and dass21_totals <- left_join(dass21_totals, dass21_stress) .

**Comment by paulsharpeY** [comment]
Probably mostly for Andy in terms of wider syllabus, but I would use `pivot_longer()` for this, and because pivoting is such a useful technique to understand.

My experience from PSYC753 is that you need a full worksheet/workshop with lots of visuals and practice for the idea to land. (Maybe timetable around lectures on mental rotation!)

Ben's materials: https://benwhalley.github.io/datafluency/data-wrangling1.html#pivotlonger
Visalize using real data: https://tidydatatutor.com/vis.html

**Comment by ajwills72** [comment]
I spent a while thinking about this, but in this particular case I don't think the mis-counting risk is particularly high, and the code as stands is shorter and I think easier to follow than the - admittedly more more tidyverseic - alternative suggested by Jon. I seem to remember going through the same thought process a few years back when Paul first wrote the work sheet using rowSum, and I thought it would be nicer to do this in a long-format manner, but then felt the overhead for the students was too great to justify.

Jon - If you'd like something more in the format you describe for the benefit of your dissertation students, I'd be happy for you to write a worksheet for the case study section of RMINR.

**Comment by benwhalley** [comment]
Sorry to come to this late but only noticed the GitHub email now. 

Isn't there a middle way here?

```
mtcars %>% 
  mutate(gearsandcylinders = mtcars %>% select(gear, cyl) %>% rowSums) %>% 
  select(gear, cyl, gearsandcylinders)
```


Or actually, I would use the `.` to sum the incoming data from the pipe) because it has the advantage that 
you can act on pre-filtered data, e.g.:

```
mtcars %>% 
  filter(wt > 2) %>% 
  mutate(gearsandcylinders = select(., gear, cyl) %>% rowSums) %>% 
  select(gear, cyl, gearsandcylinders)
```

This avoids the problem of column counting, or data later on arriving in a different order than you expected.
I think referring to dataset columns by index position is definitely an anti pattern for real research code.

**Comment by ajwills72** [comment]
OK, so, turns out (unsurprisingly), there are at least three ways to do this in R - the way currently on the worksheet, "Jon's other way" (also endorsed by Paul, I think?), and "Ben's middle way". Ben's approach is somewhat appealing to me, but it requires a re-write, and someone would need to volunteer to do that for it to happen. Any takers? I plan to release the 2022 version today, so this would be for the 2023 version now.

If there are takers, please make sure you talk to Sonja Heintz before changing things - she is currently responsible for the delivery of this material as part of the PSYC605 skills packages, and would at least need advance warning that the materials she uses are going to change. Ideally, these would be changed in consultation with her.

**Comment by ajwills72** [comment]
Just a note that this task is currently unassigned, and that I am not going to assign it to myself. If anyone else would like to take it on for the 2023 edition, let me know and I'll assign you. If no-one's volunteered by 1st June 2023, I'll mark as 'wontfix' and close.
