### ISSUE TITLE
Illustrating Bayes Factors

### ISSUE THREAD

**Issue by ajwills72** [ajwills72/rminr#52]
[BayesFactor Chart.pptx](https://github.com/ajwills72/rminr/files/8255944/BayesFactor.Chart.pptx)

Shaun Dordoy generated the above illustration of Bayes Factors, maybe convert to Rmarkdown and include in materials?

**Comment by ajwills72** [comment]
Add to "Evidence" page, add yourself and Shaun to author list of page.

**Comment by ajwills72** [comment]
May also want to link to this somewhere? (Suggested by Matt Roser)
Bayes for Babies read through.

[https://www.youtube.com/watch?v=CcnLnKU26dg](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCcnLnKU26dg&data=05%7C01%7Candy.wills%40plymouth.ac.uk%7C41230467d6434c95f92008da6fd0afca%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637945239332951247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YMxNX9HVX4QpSdPPACF%2FLR%2FzkUQB%2FnjS8RL2gXfSX4M%3D&reserved=0)

**Comment by lenarddome** [comment]
I think there is a mismatch between the material and the video, because the worksheet teaches Bayes Factors while the video explains Bayesian Parameter Estimation (Kruschke's method).

I will not include it in Evidence for now.

**Comment by ajwills72** [comment]
The commit for the Table looks good on the face of it. Can you please include in the 2022-edition branch. I'll do a final review when I pass through that page and then close the issue :-)

**Comment by lenarddome** [comment]
No problem. Changes are already there  🌝

**Comment by ajwills72** [comment]
Yep, this is great!
