### ISSUE TITLE
Fix colours in src/evidence.Rmd

### ISSUE THREAD

**Issue by benwhalley** [ajwills72/rminr#57]
I wanted to steal the new coloured table of Raftery BF rules of thumb and was puzzled by the colouring.

I don't know how to fix it, but wanted to highlight the weird color order... I think the code isn't doing what might be expected. The colouring is happening based on the sort order of the text in the cell, not based on the position in the vector of colours passed in from the color palette.

For now I have just used a B&W table, but think it might be worth changing these colours because they actually distract from the ordering/magnitude of the data in the table.

**Comment by lenarddome** [comment]
Hey, Ben!

You are right, somethings is going amiss in the coloring. Even though I used 5 colors, the output seems to contain more than 5, which is annoying. If you look at the row html, you can see that the command output different but similar colors:

```html
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>A rule-of-thumb interpretation of Bayes Factors</td>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">Bayes Factors</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">Interpretation</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">&gt; 100</td>
<td class="gt_row gt_left" style="background-color: #FBBB20; color: #000000;">Extreme evidence for the alternative hypothesis</td></tr>
    <tr><td class="gt_row gt_left">30 - 100</td>
<td class="gt_row gt_left" style="background-color: #8B226A; color: #FFFFFF;">Very strong evidence for the alternative hypothesis</td></tr>
    <tr><td class="gt_row gt_left">10 - 30</td>
<td class="gt_row gt_left" style="background-color: #C73E4C; color: #FFFFFF;">Strong evidence for the alternative hypothesis</td></tr>
    <tr><td class="gt_row gt_left">3 - 10</td>
<td class="gt_row gt_left" style="background-color: #F1721E; color: #000000;">Moderate evidence for the alternative hypothesis</td></tr>
    <tr><td class="gt_row gt_left">1 - 3</td>
<td class="gt_row gt_left" style="background-color: #FCFFA4; color: #000000;">Anecdotal evidence for the alternative hypothesis</td></tr>
    <tr><td class="gt_row gt_left">0.33 - 1</td>
<td class="gt_row gt_left" style="background-color: #F4E157; color: #000000;">Anecdotal evidence for the null hypothesis</td></tr>
    <tr><td class="gt_row gt_left">0.10 – 0.33</td>
<td class="gt_row gt_left" style="background-color: #E05536; color: #FFFFFF;">Moderate evidence for the null hypothesis</td></tr>
    <tr><td class="gt_row gt_left">0.03 – 0.10</td>
<td class="gt_row gt_left" style="background-color: #A92E5E; color: #FFFFFF;">Strong evidence for the null hypothesis</td></tr>
    <tr><td class="gt_row gt_left">0.01 – 0.03</td>
<td class="gt_row gt_left" style="background-color: #6B186E; color: #FFFFFF;">Very strong evidence for the null hypothesis</td></tr>
    <tr><td class="gt_row gt_left">&lt; 0.01</td>
<td class="gt_row gt_left" style="background-color: #FB9507; color: #000000;">Extreme evidence for the null hypothesis</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="2">Note that this is BF<sub>10</sub>, which means that the larger the Bayes Factor is, the more evidence we have for the alternative hypothesis.</td>
    </tr>
  </tfoot>
```

BTW, mappings in `gt` are done by `scales:col_factor()`, according to the docs, maybe it is a good place to start.

**Comment by lenarddome** [comment]
One alternative is to simply use a continuous color scale:

```r

bf_table %>%
tab_header(title = md("A rule-of-thumb interpretation of Bayes Factors")) %>%
tab_source_note(source_note = html(paste(
        "Note that this is BF<sub>10</sub>, which",
        "means that the larger the Bayes Factor is, the more evidence we have for the",
        "alternative hypothesis."))
        ) %>%
data_color(columns = Interpretation,
           colors = scales::col_factor(palette = colors, levels = Interpretation, ordered = FALSE),
           autocolor_text = TRUE,
        ) %>%
tab_options(table.font.size = 14)
```

![image](https://user-images.githubusercontent.com/23503601/189344696-21f4a1d7-a777-491b-899c-873a119f4113.png)

which might actually be better?

**Comment by benwhalley** [comment]
Yes - I think the issue is that it is mapping the values in each cell to a color, like a heat map. I don’t know the gt package, but kable might be simpler?


On 9 Sep 2022, at 12:59, Lenard Dome ***@***.***> wrote:

﻿

One alternative is to simply use a continuous color scale:

bf_table %>%
tab_header(title = md("A rule-of-thumb interpretation of Bayes Factors")) %>%
tab_source_note(source_note = html(paste(
        "Note that this is BF<sub>10</sub>, which",
        "means that the larger the Bayes Factor is, the more evidence we have for the",
        "alternative hypothesis."))
        ) %>%
data_color(columns = Interpretation,
           colors = scales::col_factor(palette = colors, levels = Interpretation, ordered = FALSE),
           autocolor_text = TRUE,
        ) %>%
tab_options(table.font.size = 14)

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F23503601%2F189344696-21f4a1d7-a777-491b-899c-873a119f4113.png&data=05%7C01%7Cben.whalley%40plymouth.ac.uk%7C67db300cf2014b755a2808da925aad6a%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637983215398493809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r8Dm33E1dbWxIfAHtwDhhTYSd8DD%2BoV%2FZhLBYmRVVSE%3D&reserved=0>

which might actually be better?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fajwills72%2Frminr%2Fissues%2F57%23issuecomment-1241890572&data=05%7C01%7Cben.whalley%40plymouth.ac.uk%7C67db300cf2014b755a2808da925aad6a%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637983215398493809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wm6y5omWFbuQbN0z8Y1gxDr7X4SBLPQjbymJFZvRY8E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAEADGHJIZURQUUONCG6DJ3V5MRABANCNFSM6AAAAAAQIR7BLU&data=05%7C01%7Cben.whalley%40plymouth.ac.uk%7C67db300cf2014b755a2808da925aad6a%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C637983215398493809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5PyV7qBf%2Bba7CT49B9Vpra%2BiajAp4Jcfx%2FgJ4SmDgyk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by ajwills72** [comment]
Happy for you to fix this, Lenard. If you're able to do so in the next 90 minutes or so, please do that, in the 2022-edition branch.
It not, please wait for the announcement that the master branch has been updated to the 2022 edition, which I'm hoping to do today (or perhaps Monday).
