### ISSUE TITLE
An index would be helpful

### ISSUE THREAD

**Issue by tjhollins** [ajwills72/rminr#58]
As a new R-user, who isn't involved in the teaching, I often want to find out how to do something. However, there is no easy way to find a particular technique (*) other than opening a series of best-guess worksheets until I find it. It would be useful to have an **index** (that also covered Ben's materials for stage 2, and anything specialist from Stages 4 and 5). 

(*) By technique, I don't just mean a particular statistical or graphical technique, but also data processing stuff (moving from long to wide format, creating new variables that are conditional on other values etc).  

My current solution to many of these things is to use the R help, or Google, but that is inefficient (if there is guidance on our site) and also may lead to solutions other than those we teach. 

Tim

**Comment by benwhalley** [comment]
I think this might be useful: https://plymouthpsychology.github.io/cheatR/

**Comment by ajwills72** [comment]
Those are good, Ben - will add links from top page to 2023 edition.

An index (and/or a within-RMINR search function) for RMINR does sound like a valuable addition, although with >60 worksheets it's not a trivial task. Still, will aim to have these things done for the 2023 edition

**Comment by benwhalley** [comment]
It definitely isn't a trivial task. Probably a good afternoon's work for someone. There is a partial index for just the lifesavr stuff, which is here: https://benwhalley.github.io/lifesavR/#topicindex

A complete index of all mentions of a technique or command isn't that useful, which makes it harder to auto-generate ... I found that it's more useful to try and list the primary place something is explained.

**Comment by ajwills72** [comment]
Due to the decision today to phase out RStudio from teaching at UoP Psychology, this and all other issues are now closed.
